### ISSUE TITLE
Adjust site title for mobile devices

### ISSUE THREAD

**Issue by nielslange** [wcasia/theme-2020#19]
**Steps to reproduce**

- Look up http://2020.asia.wordcamp.org on a mobile device

**Expected behaviour**

Site title does not break

**Current behaviour**

Site title breaks (see screenshot below)

![IMG_5957](https://user-images.githubusercontent.com/3323310/61778684-7b651a80-adff-11e9-9d1e-e7179ee975b9.jpg)

**Comment by drebbits** [comment]
Fixed in #21 but looks like site title is just too big on mobile

@tepkenvannkorn we can try reducing the font size. Let's try `2.215em` for `.home .site-header .custom-header .site-title` as the baseline (mobile first) then back to `3.215em` for screen with min-width of `768px` to start.
