### ISSUE TITLE
Ticket Info Page: One paragraph is right-aligned

### ISSUE THREAD

**Issue by naokomc** [wcasia/theme-2020#22]
Steps to reproduce:
1. Purchase a ticket
2. Go to the ticket information screen (URL is something like https://2020.asia.wordcamp.org/tickets/?tix_action=access_tickets&tix_access_token=xxxx...)

The last paragraph is right-aligned.

![image](https://user-images.githubusercontent.com/34067/62019398-9bc71780-b1f9-11e9-9e07-c4661f9990dd.png)

That CSS for `#tix p:last-child` is set for the ticket purchase button ("Register") on  https://2020.asia.wordcamp.org/tickets/.

**Comment by drebbits** [comment]
@appsrex are you able to work on this? If not no worries, we can assign to @tepkenvannkorn or me.

**Comment by appsrex** [comment]
@drebbits i will push the updates today.
