### ISSUE TITLE
Other method for purchasing tickets for Nepal

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#23]
Is there any other method for Payment for the tickets? I am from Nepal. Our Bank cards does not works online and PayPal is not available in our country. Please let me know if there is any other method for purchasing tickets.

https://2020.asia.wordcamp.org/wp-admin/post.php?post=715&action=edit&classic-editor__forget&classic-editor

**Comment by appsrex** [comment]
I don't think we will be able to take local payments.

**Comment by drebbits** [comment]
@appsrex we have a member in the organizing team from Nepal. We can get insights from him on how they accept payments in their WordCamps.

**Comment by drebbits** [comment]
This has been taken care of by #budget and comms team thru our Freescrout help desk.

Closing out.
