### ISSUE TITLE
Error shown, even when payment was made.

### ISSUE THREAD

**Issue by utsavsinghrathour** [wcasia/theme-2020#25]
There seems to be some problem with the payment confirmation.
The payment was made but the end-user saw an error.

https://twitter.com/eblagonic/status/1155821986720956417
This particular issue has been resolved as per the discussion on Slack. Putting it here to make sure this is fixed.

**Comment by drebbits** [comment]
Thanks @utsavsinghrathour, we will reach out to central support as well to confirm if there's any payment came through from the transaction they made. Please reference this in the #budget channel as well.

**Comment by drebbits** [comment]
@appsrex saw you already acknowledged their issue on Twitter 👍

**Comment by utsavsinghrathour** [comment]
Apparently, he tried to book another ticket and then the site froze.
"It also seems I have an issue now that I bought another ticket :/ it has been freezed, now I unfreezed it and I'm not sure if the payment went through :| the last ticket was registered to my email emanuel@blagonic.com"
Can you please take a look on to it. 
@drebbits

**Comment by appsrex** [comment]
@utsavsinghrathour Found it was failed. We will decide how to proceed with failed tickets ASAP.

**Comment by drebbits** [comment]
@appsrex @utsavsinghrathour looks like this one got resolved?

**Comment by utsavsinghrathour** [comment]
Yes it was resolved. Thank you. Will also close this issue.
