### ISSUE TITLE
Set featured image for the ticket page

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#29]
https://2020.asia.wordcamp.org/tickets/

**Comment by tepkenvannkorn** [comment]
Can anyone recommend which image to use and what dimension?

**Comment by drebbits** [comment]
@tepkenvannkorn this is the featured image for Tickets page:
https://2020.asia.wordcamp.org/files/2019/07/fb_tickets-now-on-sale.png

However, we would need to hide it from showing up on the page itself. We only need to set it as featured image for social image preview.

**Comment by drebbits** [comment]
Let's close this one. I think it's not really a critical issue right now on the site.
