### ISSUE TITLE
Adding "Request a ticket invoice" page

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#33]
adding copy and form like https://2018.europe.wordcamp.org/contact/request-a-ticket-invoice/

**Comment by drebbits** [comment]
- [x] Copy the content from the [WCEU2018](https://2018.europe.wordcamp.org/contact/request-a-ticket-invoice/) as a page (do not publish yet)
- [x] Add the draft link in Ticket Invoice Request (https://docs.google.com/spreadsheets/d/1YiE4DKgW7T7yLNSb3x64kaaqLKN4bWG0DfXj3OtZryM/edit#gid=0)
- [x] Have the #budget team review the info and form in the page
- [x] Assign to @jainnidhi to reach out to comms for review/publishing

**Comment by tepkenvannkorn** [comment]
The page is now ready for review. The date will need to be specified. Link: https://2020.asia.wordcamp.org/wp-admin/post.php?post=1465&action=edit

**Comment by jainnidhi** [comment]
It's completed and published.
