### ISSUE TITLE
Update website logo

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#34]

**Comment by wittwitsan** [comment]
Logo image here: https://drive.google.com/open?id=1x21rvJ04gUcuNzU2RldZ_X_jaz9wAJYu

**Comment by wittwitsan** [comment]
Mockup of how it'd look on desktop and mobile:
https://www.figma.com/file/vDNpJTFZmNsMFQnwFNXs5M/WordCamp-Asia-2020-Website?node-id=21%3A3

**Comment by drebbits** [comment]
thanks, @ibdz

**Comment by drebbits** [comment]
@ibdz can you look at the PR (https://github.com/wcasia/theme-2020/pull/36)?
