### ISSUE TITLE
The Design team is looking at the preferences for fonts in each language.

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#37]
For Japanese, we want only the title “M PLUS 1p”. Specify only “sans-serif” for the text. Because Japanese web fonts are heavy and affect speed, we decided not to apply them in the body of text.

https://fonts.google.com/specimen/M+PLUS+1p

**Comment by nukaga** [comment]
For Chinese, please use "Noto Sans TC"
https://fonts.google.com/specimen/Noto+Sans+TC

**Comment by drebbits** [comment]
@appsrex would you like to work on this?

**Comment by appsrex** [comment]
@drebbits on it

**Comment by imnok** [comment]
@ibdz can you choose one for Thai, please?

**Comment by appsrex** [comment]
> @ibdz can you choose one for Thai, please?

Yes. I was about to ask you on slack. can you leave the font link here?

**Comment by wittwitsan** [comment]
**Font for Thai language:**

Heading font:
https://fonts.google.com/specimen/Mitr

Body font:
https://fonts.google.com/specimen/Sarabun

**Comment by drebbits** [comment]
@appsrex any updates here? Do you need assistance, we can pull in VK.
