### ISSUE TITLE
Create call for wapuu Jetpack form

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#38]
https://2020.asia.wordcamp.org/?p=1787&preview=true

- name
- org account
- E-mail address
- Consent to WordCamp volunteer, executive committee, speaker agreement
- Wapuu’s 100% GPL agreement
- Wapuu file share URL
- Short comment to introduce Wapuu

**Comment by jainnidhi** [comment]
I've created this form. Please check and let me know.
https://2020.asia.wordcamp.org/?p=1787&preview=true

**Comment by tepkenvannkorn** [comment]
Hi @jainnidhi and @drebbits, besides "Short comment to introduce Wapuu" field, should other fields be required?

**Comment by drebbits** [comment]
A couple of notes here. Sorry I added the fields without any field type.

name - textfield (req)
org account - textfield 
email address - email add (req)
wapuu's file share URL - textfield / URL field (req)
short commend to introduce wapuu - textarea (req)
consent to WordCamp volunteer etc (add link to the agreement) - checkbox
Wapuu 100% GPL agreement (add link to the agreement) - checkbox

**Comment by jainnidhi** [comment]
@drebbits Comms team have been amended the form. And the post is live now.
https://2020.asia.wordcamp.org/2019/09/02/call-for-wapuu/

So, we can close this. :)
