### ISSUE TITLE
Main language pages

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#39]
Review the pages under **Languages** in our Website Sitemap - https://docs.google.com/spreadsheets/d/1YiE4DKgW7T7yLNSb3x64kaaqLKN4bWG0DfXj3OtZryM/edit#gid=0

**Comment by jainnidhi** [comment]
@drebbits I've checked the main translation pages. Venue details added on Japanese page but not on other translation pages.
And Info page don't have the venue details. Maybe that's why all translated these pages accordingly.
So, do we need to add the venue details on all the pages?
And the last "What is WordCamp" description is also different on all pages.

**Comment by drebbits** [comment]
@jainnidhi do you mean by venue details is Japanese has the google map embed? Let's add the google map embed to other translated pages if they are missing, and I don't think we need to worry about the "What is WordCamp".

Sam from communication approved these pages so go ahead and published them when you get a chance. Ideally today or tomorrow.

**Comment by drebbits** [comment]
Once published, feel free to add to the top menu following our sitemap structure.

**Comment by jainnidhi** [comment]
Hey @drebbits I've added map on all the pages and also published them.
Do I need to add as a sub pages of home page or create a Languages link in menu and then add as a sub pages in it?

It would be better if we add as sub pages for home page.

What do you think?

**Comment by drebbits** [comment]
For AR from Ali:
```
.page-slug-ar {
    direction: rtl;
}
.page-slug-ar #primary {
    text-align: right;
}
```

**Comment by drebbits** [comment]
@jainnidhi I can see why we can have it under homepage, too. I think for me, it's more on people  used to **not** have any subpages on `Home`, and typically multi-languages site will either have flag in the header or footer; or a cue or text that would hint them languages is available here or under here.

Example:
https://2019.tokyo.wordcamp.org/
https://2018.tokyo.wordcamp.org/

I'd say let's add a language link per your second option as a start; then let's write a P2 as an update that languages is now available and get their feedback?

**Comment by appsrex** [comment]
> For AR from Ali:
> 
> ```
> .page-slug-ar {
>     direction: rtl;
> }
> .page-slug-ar #primary {
>     text-align: right;
> }
> ```

We better do it using parent page id

**Comment by drebbits** [comment]
@appsrex or @tepkenvannkorn are you able to make the changes to make the Arabic text direction RTL? Example CSS is in the previous comment above.
