### ISSUE TITLE
Invitation Letter Request Page

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#41]
Example visa invitation letter:

https://2019.us.wordcamp.org/info/visa-letter-requests/
https://2019.bangkok.wordcamp.org/invitation-letter-request/

- [ ] Copy the content from [WCBKK2019](https://2018.europe.wordcamp.org/contact/request-a-ticket-invoice/) as a page (do not publish yet)
- [ ] Add the draft link in Invitation Letter Request (https://docs.google.com/spreadsheets/d/1YiE4DKgW7T7yLNSb3x64kaaqLKN4bWG0DfXj3OtZryM/edit#gid=0)
- [x] Have the #attendees-experiences team to (1) update the copy/info, and (2) review form in the page
- [x] @jainnidhi to reach out to comms for review/publishing

**Comment by drebbits** [comment]
https://trello.com/c/hHQz4nko/1-template-visa-invitation-letter

**Comment by jainnidhi** [comment]
Hey @drebbits I've created this page.
Please check and let me know.
https://2020.asia.wordcamp.org/?page_id=12148&preview=true
