### ISSUE TITLE
Texts appear shorter than then layout on page "Interactive Map Guide"

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#44]
The first para on the site appears shorter than the rest of the block.
<img width="683" alt="Screen Shot 2019-09-06 at 10 43 56" src="https://user-images.githubusercontent.com/6930425/64400220-a9dc4380-d095-11e9-9e10-162cec32e991.png">
https://2020.asia.wordcamp.org/?page_id=11884&preview=true

**Comment by appsrex** [comment]
> The first para on the site appears shorter than the rest of the block.
> <img alt="Screen Shot 2019-09-06 at 10 43 56" width="683" src="https://user-images.githubusercontent.com/6930425/64400220-a9dc4380-d095-11e9-9e10-162cec32e991.png">
> https://2020.asia.wordcamp.org/?page_id=11884&preview=true

This is happening for the words that are the end of the line, justifying them will look bad

**Comment by tepkenvannkorn** [comment]
@appsrex 100% agree. @drebbits should we ping the comms team to change the copy or just leave as it is right now?

**Comment by drebbits** [comment]
@tepkenvannkorn let's leave it as is for now. I don't see this one as critical / interfering with reading experience. Thanks for exploring this VK!

Closing this one.
