### ISSUE TITLE
Add Sponsor list and sponsor details page

### ISSUE THREAD

**Issue by nukaga** [wcasia/theme-2020#48]
Please display the sponsor list in the footer and create a sponsor details page.
The design is this Figma v3 Footer-sponsors list and Sponsor single page.
https://www.figma.com/file/vDNpJTFZmNsMFQnwFNXs5M/WordCamp-Asia-2020-Website?node-id=134%3A106

**Comment by drebbits** [comment]
Sponsors page:
https://2020.asia.wordcamp.org/wp-admin/post.php?post=10&action=edit

Sponsors block:
<img width="728" alt="Screen Shot 2019-10-11 at 9 14 25 PM" src="https://user-images.githubusercontent.com/5811397/66654184-40d78500-ec6c-11e9-9c19-5efcd170deaa.png">

**Comment by Kenshino** [comment]
Hey - has this been completed?

I believe we asked for this to be finished by 9 October and the sponsor listing page doesn't look completed yet.

**Comment by appsrex** [comment]
> Please display the sponsor list in the footer and create a sponsor details page.
> The design is this Figma v3 Footer-sponsors list and Sponsor single page.
> https://www.figma.com/file/vDNpJTFZmNsMFQnwFNXs5M/WordCamp-Asia-2020-Website?node-id=134%3A106

On it

**Comment by drebbits** [comment]
Thanks, @appsrex! I have a follow up changes ready that I can merge later in the morning.

**Comment by drebbits** [comment]
@Kenshino page is ready. We are only missing featured image and content for Themeum (https://2020.asia.wordcamp.org/wp-admin/post.php?post=12315&action=edit).

Sponsors page:
https://2020.asia.wordcamp.org/sponsors

Single page:
https://2020.asia.wordcamp.org/sponsor/paypal/

It's likely for testing but wanted to ask anyway if several sponsor levels per sponsor is intentional.
![Screen Shot 2019-10-15 at 12 13 05 PM](https://user-images.githubusercontent.com/5811397/66800032-36f0a300-ef46-11e9-9239-14ffb1e33b13.png)

**Comment by nukaga** [comment]
Thank you! @drebbits @appsrex
I think it is better to have a logo in the center when there is only one sponsor in the same sponsor hierarchy in the sponsor list.

**Comment by drebbits** [comment]
@nukaga does the #designteam have specific design for this for mobile? Right now, they just stack up — each logo is full width.

WCASIA 2020 Sponsors
![IMG_1649](https://user-images.githubusercontent.com/5811397/67467718-dcf58900-f67b-11e9-80b8-90b678f6c5d4.PNG)

Are you looking similar layout as on WCUS 2019 Sponsors page (https://2019.us.wordcamp.org/sponsors/)
![IMG_1650](https://user-images.githubusercontent.com/5811397/67467809-0c0bfa80-f67c-11e9-87ba-383ece92423a.PNG)

**Comment by drebbits** [comment]
@ibdz @nukaga 

@appsrex has a feedback:
> How about we make the design so that logos stand out more? Now it seems like we're promoting the package name with large size text and putting the title on the center( which is okay). But i would still want to see the logo stands out.

I do get his point, level name headings are bigger than the logos which you can start noticing from Asok down to Nana.

Looking at other WordCamps for inspiration (if it helps):

WCEU2019 has smaller headings
https://2019.europe.wordcamp.org/sponsors/

WCUS2019 puts the logos in a box:
https://2019.us.wordcamp.org/sponsors/

Adding to this list is WCBKK2019 (https://2019.bangkok.wordcamp.org/sponsors/) if we don't have that many sponsors to merit putting them in a grid.

**Comment by wittwitsan** [comment]
@drebbits I agree that the level name headings are too big. I'm thinking of adding the divider line between each level, that might help.

WCUS2019 is what I'm looking for. I feel that the image size of Nana is too small, I will adjust and get back to you asap.

**Comment by drebbits** [comment]
Pulled from the [#website](https://wcasia.slack.com/archives/CJZ0CRN7J/p1572084313017500) Slack channel:

> - Change Sponsors title heading from 2.441rem to 1.563rem (28.13px)
> - Add divider line beside title
> - Change title color to Primary/Red-300 (#EF8162)
> - Margin between logo is 32px horizontal / 24px vertical

![image](https://user-images.githubusercontent.com/5811397/67619141-811d3280-f82a-11e9-8e29-a92fa3a2e029.png)

Container width 960px (added negative margin on left -16px/right -16px)
Size of each sponsor item: (margin: 0 16px 24px 16px)
Siam - 50%
Silom - 33.3333%
Asok - 25%
Ari - 20%
Nana / In-Kind - 16.6667%


### Mobile
Go with similar layout of WCUS Sponsors page
> Si-am - 100%
> Silom - 50%
> Other - 33.33%

**Comment by drebbits** [comment]
@ibdz looking at how you align Shifter and Seed Themes in the mock-up, and It's pretty complicated to apply that to all the logos as not all would look good with that alignment.

Here's our progress that I posted in another PR:
https://github.com/wcasia/theme-2020/pull/53#issue-335287031

We could tweak just for Nana for better logo alignment:
<img width="386" alt="Screen Shot 2019-11-01 at 1 54 25 PM" src="https://user-images.githubusercontent.com/5811397/68005341-e7cda080-fcaf-11e9-8205-beec97e34d7d.png">

**Comment by drebbits** [comment]
@tepkenvannkorn can you help look at why the other levels are not in their correct number of sponsors per row?

<img width="536" alt="Screen Shot 2019-11-12 at 4 10 57 PM" src="https://user-images.githubusercontent.com/5811397/68653656-2a706200-0567-11ea-9e42-dd738b221183.png">

For reference: 
Siam - 2 sponsors per row
Silom - 3 sponsors per row
Asok - 4 sponsors per row
Ari - 5 sponsors per row
Nana - 6 sponsors per row

**Comment by drebbits** [comment]
@tepkenvannkorn also take a look at the individual sponsors page if they are consistent. We can give a hand to Sponsors team to build these single sponsor pages.

**Comment by drebbits** [comment]
Here's the confirmed number of sponsors per row per level per the @sponsorsteam:

Siam and Silom: 2
Asok: 3
Ari: 4
Nana: 5

As noted earlier in the thread here, they are also exploring the idea of having a background to the sponsors logo and boxed in a rectangular container (similar to WCUS 2019 - https://2019.us.wordcamp.org/sponsors/)

See PR #58

**Comment by drebbits** [comment]
Moving my feedback in here:

@tepkenvannkorn after previewing the changes in customizer, here are my feedback:

**A.** the sideline doesn't seem to play nicely with the grid especially that it's not align with the left and right edges of the grid. Let's remove that for now if it's going to be a challenge aligning the sideline with the grid.

**B.** reduce the width of the logo images of Silom sponsors. This is what going to separate the Silom from Siam (being Siam sponsors paid more than Silom). In my test, looks like adding width: 60% should work (let's make sure it's center aligned) - but you can definitely suggest another width size.

<img width="423" alt="Screen Shot 2019-11-27 at 3 21 17 PM" src="https://user-images.githubusercontent.com/5811397/69702645-a6070d00-112a-11ea-8d86-a0251f9898c9.png">

**Comment by drebbits** [comment]
@tepkenvannkorn we are awaiting for the key visual from the design team. Once we have that, we should be able to finalize the layout for the sponsors page.

**Comment by drebbits** [comment]
@tepkenvannkorn have you already addressed my feedback here https://github.com/wcasia/theme-2020/issues/48#issuecomment-559515988? Let's go ahead and make changes for that. Design team wanted to see the changes first before they look at it.

Please setup customizer with the updated changes there so we could QA.

**Comment by drebbits** [comment]
Sorry for any confusion here. My feedback above is referring to this pull request https://github.com/wcasia/theme-2020/pull/74

**Comment by drebbits** [comment]
@tepkenvannkorn update here? Please share the new Sponsors page to the design team to test.

**Comment by drebbits** [comment]
Approved by the design team.

Please have it reviewed by the sponsors team. In-Kind are placeholders only so they could see how would it look like there.

https://2020.asia.wordcamp.org/sponsors-blocks/

**Comment by drebbits** [comment]
@tepkenvannkorn sorry, I noticed one thing on mobile. Before we send over to Sponsors team could we please address it first?

1. On smaller screens, sponsors are stack up. Let's make the logos to be 2x2 (except Siam) starting from 360px and until it shifts to their corresponding logos per row.

Currently:
<img width="291" alt="Screen Shot 2019-12-09 at 6 55 47 PM" src="https://user-images.githubusercontent.com/5811397/70430901-bfa73d80-1ab6-11ea-9dc2-4f63b03c1bca.png">

What we like to have:
<img width="289" alt="Screen Shot 2019-12-09 at 6 56 50 PM" src="https://user-images.githubusercontent.com/5811397/70430852-a30b0580-1ab6-11ea-850b-1be5a635a4e8.png">

2. Keep Siam logos one per row until max width 700px

3. Add margin bottom (around `1rem`) to all logos so it has a gap when they stack up

What we like to have:
<img width="248" alt="Screen Shot 2019-12-09 at 6 57 37 PM" src="https://user-images.githubusercontent.com/5811397/70430839-9b4b6100-1ab6-11ea-9941-6c55a6623286.png">

**Comment by drebbits** [comment]
@tepkenvannkorn please have sponsors team review and get approval if all looks good for them. Great work here by the way!

**Comment by tepkenvannkorn** [comment]
Yes, done.
