### ISSUE TITLE
Payment Error on Tickets“Your form submission could not be processed. Please try again.”

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#54]
Original message:
Message: Hello Team, hope you all are doing well!
Earlier today, I was trying to purchase (4) tickets to WordCamp Asia. After initiating the payment, I was displayed with an error “Your form submission could not be processed. Please try again.”
I tried to make the payment through a credit card with Stripe. Attached is a screenshot of the error - https://www.evernote.com/l/AgdxxFInhPVMqYQ4aqPEeeUfQUucTMZsmWE
Kindly assist me in making the purchase. Thank you for your help.

**Comment by drebbits** [comment]
JC responded to the reporter. Closing.
