### ISSUE TITLE
Add logos of media partners to the Press page

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#57]

**Comment by drebbits** [comment]
For:
https://2020.asia.wordcamp.org/press/

At the moment we have only names listed. We promised we would have their logo on our websites. Currently 8 MPs, it would be 9.

Logos:
https://docs.google.com/spreadsheets/d/1ILw1Gv4_079JLp1x-SfZkE1BMVuPwsFfPTkbGp9j1XI/edit#gid=732023376

**Comment by appsrex** [comment]
> For:
> https://2020.asia.wordcamp.org/press/
> 
> At the moment we have only names listed. We promised we would have their logo on our websites. Currently 8 MPs, it would be 9.
> 
> Logos:
> https://docs.google.com/spreadsheets/d/1ILw1Gv4_079JLp1x-SfZkE1BMVuPwsFfPTkbGp9j1XI/edit#gid=732023376

Added 8 logos

**Comment by appsrex** [comment]
Added MP's Logo using 3 column layout

**Comment by drebbits** [comment]
thanks @appsrex !

**Comment by drebbits** [comment]
Looks great.
