### ISSUE TITLE
Add Speakers & Sessions - Content Speakers

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#66]
Refer to Announcement Round => `3` column in the `Website Sitemap > Speakers` & `Website Sitemap > Sessions`. We need to add them in order of when they are announced.

- [x] Add draft Speakers (do not publish yet)
- [x] Add draft Sessions (do not publish yet)
- [x] Ping and assign this to @drebbits to update comms and speakers teams in Trelllo

### Add draft speaker page notes
- Add the speaker edit page URL in the sheet under Speakers tab > `Speaker Page` column
- Add bio both to post content and excerpt
- Example speaker page - https://2020.asia.wordcamp.org/wp-admin/post.php?post=14045&action=edit

### Add draft session page notes
- Add the session edit page URL in the sheet under Sessions tab > `Session Page` column
- No need to fill in the session info
- No need to fill in excerpt
- Example session page - https://2020.asia.wordcamp.org/wp-admin/post.php?post=14011&action=edit

**Comment by drebbits** [comment]
Description updated with more notes.

**Comment by jainnidhi** [comment]
I've drafted all the speakers and sessions for 3rd round. :)
