### ISSUE TITLE
Add Contributor Day page

### ISSUE THREAD

**Issue by naokomc** [wcasia/theme-2020#67]
I've received 2 comments from attendees that they are not sure when Contributor Day is.
Could you make this information more visible? 

https://2020.asia.wordcamp.org/info/ has this info but is not visibly linked.

**Comment by drebbits** [comment]
While we wait for the Contributor Day page to be created, we can add a link in the top nav to link to say https://2020.asia.wordcamp.org/info/#date temporarily.

**Comment by drebbits** [comment]
@jainnidhi let's reach out to Contributor Day team to check the status of our schedule for this day.

**Comment by jainnidhi** [comment]
@drebbits Contributor page is live now.
https://2020.asia.wordcamp.org/contributor-day/
So we can close this ticket.

**Comment by drebbits** [comment]
@jainnidhi that's right. Let's close this one.
