### ISSUE TITLE
Add Speakers & Sessions - Business Speakers

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#69]
Refer to Announcement Round `4` in the `Website Sitemap > Speakers` & `Website Sitemap > Sessions`. We need to add them in the order of when they are announced.

- [ ] Add draft Speakers (do not publish yet)
- [ ] Add draft Sessions (do not publish yet)
- [ ] Ping and assign this to @drebbits to update comms and speakers teams in Trelllo

### Add draft speaker page notes
- Add the speaker edit page URL in the sheet under Speakers tab > `Speaker Page` column
- Add bio both to post content and excerpt
- Example speaker page - https://2020.asia.wordcamp.org/wp-admin/post.php?post=14045&action=edit

### Add draft session page notes
- Add the session edit page URL in the sheet under Sessions tab > `Session Page` column
- No need to fill in the session info
- No need to fill in excerpt
- Example session page - https://2020.asia.wordcamp.org/wp-admin/post.php?post=14011&action=edit

**Comment by drebbits** [comment]
@appsrex I moved the due to tomorrow (earlier) so comms team will have some time to check/QA.

**Comment by drebbits** [comment]
Refer to Announcement Round `4` in our sheet (we had some changes from our latest call with the comms/speakers/design

**Comment by coderexco** [comment]
Sessions & Speakers bio has been added( draft)

**Comment by appsrex** [comment]
Sessions & Speakers' bio has been added.

**Comment by drebbits** [comment]
I shared the speakers and sessions WP page urls to the com/spe/des teams.
