### ISSUE TITLE
Add Speakers & Sessions - Mixed

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#72]
Refer to Announcement Round `7` in the `Website Sitemap > Speakers` & `Website Sitemap > Sessions`. We need to add them in the order of when they are announced.

- [ ] Add draft Speakers (do not publish yet)
- [ ] Add draft Sessions (do not publish yet)
- [ ] Ping and assign this to @drebbits to update c/s/d teams in Trello

### Add draft speaker page notes
- Add the speaker edit page URL in the sheet under Speakers tab > `Speaker Page` column
- Add bio both to post content and excerpt (make sure format and paragraph counts match)
- Twitter URL starts with http://twitter.com/xxxx
- Set/assign the proper `Groups`
- Example speaker page - https://2020.asia.wordcamp.org/wp-admin/post.php?post=14045&action=edit

### Add draft session page notes
- Add the session edit page URL in the sheet under Sessions tab > `Session Page` column
- No need to fill in the session info
- No need to fill in excerpt
- Example session page - https://2020.asia.wordcamp.org/wp-admin/post.php?post=14011&action=edit

**Comment by drebbits** [comment]
Please make sure to read the speakers and sessions notes in the description. Thanks!

**Comment by coderexco** [comment]
Added as much info found there.

**Comment by drebbits** [comment]
@coderexco please take a look at the sheet again. I've setup the final list of the round 7 speakers and sessions with their bio.

Some speakers and sessions have already added but review them if they have the right format.

**Comment by appsrex** [comment]
checked and updated.

**Comment by drebbits** [comment]
Shared to com/spe teams.
