### ISSUE TITLE
Add Speakers listing page

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#75]

**Comment by jainnidhi** [comment]
I've set up this page.
https://2020.asia.wordcamp.org/?page_id=8&preview=true

**Comment by drebbits** [comment]
@jainnidhi I updated with these changes:

- I removed the twitter so less of noise and links for people to click when they stumbled in the speakers listing page
- Changes from full to excerpt
- Make the layout more consistent with the announcement posts

Next step here is to send the draft page to communications team for review and publish.

**Comment by drebbits** [comment]
Thanks for you help here, @jainnidhi. I notified comms team that Speakers archive page is ready.
