### ISSUE TITLE
Can't edit info using the link generated by [ticket_url]

### ISSUE THREAD

**Issue by drebbits** [wcasia/theme-2020#81]

**Comment by tepkenvannkorn** [comment]
> @Sam Suresh @Dreb Bits - @Nok just found a bug/issue in the purchase ticket email. The [ticket_url] shortcode sent over the access url instead of the edit url so attendees (including us) can't edit their details. It would be good to send out an email blast with their ticket url just in case they want to edit. Coz right now, it just shows them the ticket info and there's no way to edit it. I just tested the shortcode and it works fine now - but just fyi because people who want to edit their tickets can't do it.

**Comment by jainnidhi** [comment]
I've fixed it.
When I tried to edit the info, there was a question “May we contact you… ” which was required and haven't selected any option. So I've set that to **not required** in Standard ticket.

**Comment by imnok** [comment]
🙌 @jainnidhi Thank you for looking at this.

The issue is about the ”Edit Information” link disappear from ticket access Link page, but now it back to what it should be - so at this moment anyone can access to their ticket information and update it 🙂
