### ISSUE TITLE
Add Contributor Day & Conference Day info on the home page

### ISSUE THREAD

**Issue by jainnidhi** [wcasia/theme-2020#82]
We need to make it clear that 21st is the Contributor Day and 22/23 are the conference days.
We can add on the home page or in the banner and other areas.

**Comment by drebbits** [comment]
@tepkenvannkorn looks great for me. Can we please get design and comms teams' approval before we deploy the code changes? Thanks for work here!

**Comment by tepkenvannkorn** [comment]
Cool. I now get the approval from both teams.
