### ISSUE TITLE
Make Siam and Silom look different

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#85]
We want to make a difference between Siam and Silom. Is there a good idea? (a little bigger, border, shadow or something)

**Comment by appsrex** [comment]
> We want to make a difference between Siam and Silom. Is there a good idea? (a little bigger, border, shadow or something)

Will look at it

**Comment by drebbits** [comment]
@appsrex given @tepkenvannkorn  worked on the Sponsors page before, I think we'll have him work on this, too. However, let us know your thoughts or suggestions how we can better identify Siam and Silom sponsors better visually.
