### ISSUE TITLE
Sponsor Logos messed up

### ISSUE THREAD

**Issue by sam-suresh** [wcasia/theme-2020#92]
![screencapture-2020-asia-wordcamp-org-schedule-2020-01-20-12_15_35](https://user-images.githubusercontent.com/5198092/72698320-b792f100-3b7e-11ea-803c-fd39dc578795.png)

**Comment by drebbits** [comment]
@sam-suresh thanks for reporting this. Some changes were publish in Customizer Friday last week, and that published work in above footer Sponsors that shouldn't made public. I removed the widget and it's in shape now.
