### ISSUE TITLE
Add Key Visual into website header (homepage)

### ISSUE THREAD

**Issue by wittwitsan** [wcasia/theme-2020#95]
After waiting for so long, it's time to iterate the website header with the Key Visual.
![Website-Desktop-03](https://user-images.githubusercontent.com/426383/73139545-a3c91c80-40a1-11ea-819c-dc2d14a9ab3d.png)

Background assets here: https://drive.google.com/open?id=1DNwXZg-th9WsdEon7DHq06EEDUMEA1X4

- [ ] WordCamp Asia 2020 -> Rubik / Bold / font-size 30.17px / line-height 36px / #D73534
- [ ] February 21-23, Bangkok, Thailand -> Roboto Slab / Regular / font-size 16.97px / line-height 22px / #36393B
- [ ] Space between logo and "WordCamp Asia 2020" -> 19px
- [ ] Space between "WordCamp Asia 2020" and "February 21-23, Bangkok, Thailand" -> 4px

**Comment by tepkenvannkorn** [comment]
@drebbits should we keep "21st Contributor Day / 22nd & 23rd Conference Day"?

**Comment by drebbits** [comment]
@tepkenvannkorn let's keep it for now. Thanks for the updates here!
